### PR TITLE
Ada secondary stack support

### PR DESCRIPTION
**Pull request by jklmnn**
I added support for the [Ada secondary stack](https://docs.adacore.com/gnat_ugx-docs/html/gnat_ugx/gnat_ugx/the_stacks.html#the-secondary-stack). In this process I also did the required modifications to the ada library to use custom implementations of runtime parts.

### CODE REVIEW

**Comment by jklmnn** [comment]
With https://github.com/genodelabs/genode/pull/2810/commits/1912f8747bd86c646b325dafab8cb516dfafddc6 I revised the directory structure of `libports/src/lib/ada` to contain the runtime and (in the future) further ada libraries (e.g. a Genode package that provides Genode interfaces to Ada).
Currently it contains:
 - `.../ada/runtime`: the pure ada runtime files as they would be in the compiler sources
 - `.../ada/runtimelib`: any further implementations of runtime functionality, C glue code, C++ implementations etc.

**Comment by chelmuth** [comment]
@jklmnn I'm not sure if all changes of this PR were merged already. Could you please have a look at staging?

**Comment by jklmnn** [comment]
The first changes are already merged into staging. But https://github.com/genodelabs/genode/pull/2810/commits/234d9bcc011774e8a60470a0bfce2087cd34fabe and https://github.com/genodelabs/genode/pull/2810/commits/1912f8747bd86c646b325dafab8cb516dfafddc6 are missing.

**Comment by chelmuth** [comment]
Hm...
```
> git cherry-pick 234d9bcc011774e8a60470a0bfce2087cd34fabe
error: could not apply 234d9bc... fixup: "ada: secondary stack support" (check compiler version)

> git cherry-pick 1912f8747bd86c646b325dafab8cb516dfafddc6
On branch staging
...
    git commit --allow-empty
```
Could you please rebase? Thanks in advance.

**Comment by jklmnn** [comment]
Oh I missed that you included the two fixup commits into https://github.com/genodelabs/genode/commit/5f71c68dada79199ddde84f93f9bda976813cbc0. So there are all changes merged to staging.

**Comment by chelmuth** [comment]
Thanks for checking this.

**Comment by chelmuth** [comment]
Merged with 18.05.

**Pull request closed without merging**
