### PR TITLE
os: added framebuffer driver that uses the multiboot2 framebuffer

### PR DESCRIPTION
**Pull request by jklmnn**
I implemented a framebuffer service that uses the framebuffer provided by multiboot2. This PR just contains the driver for Genode. Since it requires an adapted hypervisor information page, it needs a patched NOVA. As it wasn't possible to add the additional fields at the end of the hip, other configuration also might need the new NOVA.
The patched NOVA can be found at https://github.com/jklmnn/NOVA/commit/07da624bf12e964389ed4bf6d1a507272876bc46 or when https://github.com/alex-ab/NOVA/pull/2 gets merged.

Furthermore it requires the changes proposed in #2242 (https://github.com/alex-ab/genode/tree/issue_2242). Since the Grub2 used here is insufficient to provide a framebuffer, you can cherry pick https://github.com/jklmnn/genode/commit/172e084f7f1fa5e2e5f9e86a62f8c38909e4993f that adds a grub with the `efi_uga` and `efi_gop` modules. It also increases the efi image size to fit the new grub.

### CODE REVIEW

**Comment by alex-ab** [comment]
Great ! I will have a look and test it as soon as I find the time. From my point of view, we will need to change a bit your implementation, to let it fit better with other x86 kernels. Using the hip of nova directly in the framebuffer renders the driver useless for them. On the #2242 branch I already introduced a specific rom in core, which contains the acpi rsdp pointer. (So reading the information from the Nova HIP and adding it the kernel independent ROM). All information you need for the efi framebuffer should be added there. This ROM would be filled with the required information by core in a kernel specific way (core is anyway kernel specific) but the final ROM would be kernel-independent for the framebuffer driver. Maybe you can rename the driver to uefi_fb_drv or so. I open for other opinions.

Again, great job !

**Comment by jklmnn** [comment]
Well, first about the naming. The according to the grub2 source it supports multiple drivers to provide a framebuffer which do not depend on (u)efi. We called it `efi_fb` before but since we use an explicit multiboot2 feature that transparently provides a framebuffer and hides the underlying driver we decided to call it as it is called now.
From `/include/grub/video.h`:
```
typedef enum grub_video_driver_id
{
      GRUB_VIDEO_DRIVER_NONE,
      GRUB_VIDEO_DRIVER_VBE,
      GRUB_VIDEO_DRIVER_EFI_UGA,
      GRUB_VIDEO_DRIVER_EFI_GOP,
      GRUB_VIDEO_DRIVER_SM712,
      GRUB_VIDEO_DRIVER_VGA,
      GRUB_VIDEO_DRIVER_CIRRUS,
      GRUB_VIDEO_DRIVER_BOCHS,
      GRUB_VIDEO_DRIVER_SDL,
      GRUB_VIDEO_DRIVER_SIS315PRO,
      GRUB_VIDEO_DRIVER_RADEON_FULOONG2E,
      GRUB_VIDEO_DRIVER_COREBOOT,
      GRUB_VIDEO_DRIVER_IEEE1275,
      GRUB_VIDEO_ADAPTER_CAPTURE,
      GRUB_VIDEO_DRIVER_XEN,
      GRUB_VIDEO_DRIVER_RADEON_YEELOONG3A
} grub_video_driver_id_t;
```

About the hip, I'm looking into the core rom, adding something kernel specific to something already kernel specific makes sense (unless we add this feature to other kernels).

One question I have is, is the location in the Genode source tree okay? I wasn't sure about that.

**Comment by jklmnn** [comment]
I made the proposed changes in https://github.com/jklmnn/genode/commit/5ce20cf4cfae1492ce15e94e7588905fd38e6eff. This however doesn't merge conflict free as it is build upon https://github.com/alex-ab/genode/commit/78056704c37f495b782a77294dc14540b6bc371b. The adapted NOVA is at https://github.com/jklmnn/NOVA/commit/df92d9f8fe9297c2919fd195ff444b3b8bdb6e89.
I mangled the framebuffer specs into the `size` and `aux` fields of `mem_desc` as I didn't see a better way.

**Comment by alex-ab** [comment]
Incorporated the commits to #2242 issue.

**Pull request closed without merging**
