### PR TITLE
base-foc: Odroid-X2 basic support, fix #1597

### LINKED ISSUE #1597: foc: Odroid-X2 support
Odroid-X2 (Exynos4412) platform support on Genode using Fiasco.OC as microkernel

### PR DESCRIPTION
**Pull request by rmillo**
Fix #1597

### CODE REVIEW

**Comment by nfeske** [comment]
This patch looks very good. The only minor detail that I'd like to see changed is the part about ``` tool/run/load/tftp_server``` as this part is not specific for the base-foc/odroid-x2 work but a general tool. In my opinion, it deserves a separate commit. Would you mind that?

**Comment by chelmuth** [comment]
First, thanks for your great contribution! I have only one little suggestion: Would you mind to name the platform `foc_odroid_x2` in `tool/create_builddir` as we already have `hw_odroid_xu`?

**Comment by rmillo** [comment]
The tool `tool/run/load/tftp_server` is an small tool that we have implemented to upload test images to a remote tftp server and then load it in the board using uboot. I have removed it from the patch (c25a8e90b4f4c28d752f6cfbfbd7a6047f1bb021).
I have renamed the platform from odroid-x2 to odroid_x2 in the script `tool/create_builddir` and files in the patch (ed8d0f44a0c12a6e296dac3e8ad1a090b85f2bee).

**Comment by chelmuth** [comment]
@rmillo according to our work flow I close this pull request and encourage you to use #1597 only for further discussion and development.

**Pull request closed without merging**
