### PR TITLE
ada-runtime: update to 1.1

### PR DESCRIPTION
**Pull request by jklmnn**
We've updated the ada runtime, see https://github.com/Componolit/ada-runtime/releases/tag/v1.1.0.

### CODE REVIEW

**Comment by chelmuth** [comment]
With your patches *test-gnatio* no longer builds.

```
> make -C build/x86_64 test/gnatio
checking library dependencies...
  Library ldso-startup
  Library ld
  Library base
  Library spark
  Program test/gnatio/test-gnatio
    COMPILE  main.o
.../genode_staging.git/repos/libports/src/test/gnatio/main.adb:7:06: file "gnat.ads" not found
.../genode_staging.git/repos/base/mk/generic.mk:86: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
var/libdeps:98: recipe for target 'test-gnatio.prg' failed
make[1]: *** [test-gnatio.prg] Error 2
Makefile:286: recipe for target 'gen_deps_and_build_targets' failed
make: *** [gen_deps_and_build_targets] Error 2

> tool/depot/create CROSS_DEV_PREFIX=genode-x86- UPDATE_VERSIONS=1 -j5 genodelabs/pkg/x86_64/test-gnatio
checking library dependencies...
  Library ldso-startup
    COMPILE  startup.o
    MERGE    ldso-startup.lib.a
  Library spark
    CONVERT  spark.symbols.s
  Library ld
    CONVERT  ld.symbols.s
    ASSEMBLE spark.symbols.o
    ASSEMBLE ld.symbols.o
    MERGE    spark.abi.so
    MERGE    ld.abi.so
  Library base
    MERGE    base.lib.a
  Program test/gnatio/test-gnatio
    COMPILE  main.o
    COMPILE  startup.o
.../genode_staging.git/depot/genodelabs/src/test-gnatio/2019-08-15/src/test/gnatio/main.adb:7:06: file "gnat.ads" not found
.../genode_staging.git/repos/base/mk/generic.mk:86: recipe for target 'main.o' failed
make[6]: *** [main.o] Error 1
make[6]: *** Waiting for unfinished jobs....
var/libdeps:99: recipe for target 'test-gnatio.prg' failed
make[5]: *** [test-gnatio.prg] Error 2
Makefile:286: recipe for target 'gen_deps_and_build_targets' failed
make[4]: *** [gen_deps_and_build_targets] Error 2
.../genode_staging.git/tool/depot/mk/build_bin_archive:200: recipe for target '.../genode_staging.git/depot/genodelabs/bin/x86_64/test-gnatio/2019-08-15.build/bin' failed
make[3]: *** [.../genode_staging.git/depot/genodelabs/bin/x86_64/test-gnatio/2019-08-15.build/bin] Error 1
.../genode_staging.git/depot/var/build.mk:24: recipe for target 'genodelabs/bin/x86_64/test-gnatio/2019-08-15' failed
make[2]: *** [genodelabs/bin/x86_64/test-gnatio/2019-08-15] Error 2
.../genode_staging.git/tool/depot/build:134: recipe for target 'execute_generated_build_mk_file' failed
make[1]: *** [execute_generated_build_mk_file] Error 2
tool/depot/create:59: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by jklmnn** [comment]
We removed GNAT.IO support so you can safely remove this test.

**Comment by chelmuth** [comment]
I'd appreciate a fixup commit from you, thanks.

**Comment by jklmnn** [comment]
https://github.com/genodelabs/genode/pull/3463/commits/4e862dbb85469b889a5a3d625533d7edf2ba81c2 removes the test and should fix it.

**Comment by chelmuth** [comment]
Merged just now.

**Comment by chelmuth** [comment]
Merged with release 19.08.

**Pull request closed without merging**
