### PR TITLE
Add Zynq-7000 support for QEMU (refactored)

### PR DESCRIPTION
**Pull request by ValiValpas**
This is a follow-up of #1569 and #1577 addressing the comments of @m-stein and @skalk.

In particular, I refactored the part that still made heavy use of preprocessor defines.

### CODE REVIEW

**Comment by m-stein** [comment]
@ValiValpas 
Thank you for taking the time to apply our comments :-) After a quick look I've merely noticed some minor style issues. I'll push some fix-ups tomorrow.

**Comment by m-stein** [comment]
@ValiValpas 
My branch [1599_Add_Zynq_7000_support_for_QEMU](https://github.com/m-stein/genode/tree/1599_Add_Zynq_7000_support_for_QEMU) re-bases your commits to our master branch and adds several fix-ups. I hope you're fine with my modifications?. I've marked your NIC refactoring as a fix-up too as it should be squashed into the original commit when finally merging. This way you're not the git author anymore but you nevertheless get mentioned in the commit message. You should anyway be mentioned as co-author in the documentation header of every file you adapted.

After all, there are still some issues left:
* I can't compile any network tests as you have missed to take over some files (marvel_phy.cc as example) from the original pull request. As these files contain lots of preprocessor defines and thus also need a more time-intensive clean-up, I would be glad if you could fix this.
* I haven't reviewed the NIC commit yet because of the above issue
* The user-land timer still shows bad behavior on ``run/signal`` at least

When fixing these things, please don't open up a new follow-up but simply put a ``Ref #1599`` in your commit messages (causes commits to be shown in this thread). This way it is much easier for others to follow the discussion and the development in the background. Please also use my [1599_Add_Zynq_7000_support_for_QEMU](https://github.com/m-stein/genode/tree/1599_Add_Zynq_7000_support_for_QEMU) branch as base for your new commitments to simplify synchronization of our collaboration.

**Comment by ValiValpas** [comment]
I assume the problem with run/signal is that the triple timer counter (TTC) I used for implementing the platform timer is only a 16bit timer. Thus the maximum possible timeout is approx. 300µs (with maximum prescaling).
Maybe we should use the Cortex A9 Global Timer instead.

**Comment by m-stein** [comment]
@ValiValpas The problem with the global timer is that resides on the same physical page as the private timers. The private timers, however, are used by the kernel for scheduling and must therefore be mapped in core only. Also using another timer in the kernel is no good idea in my opinion. We would have to find an alternative SMP-aware timer on every Cortex-A9 platform.

**Comment by m-stein** [comment]
Maybe you can use the 24 bit watchdog timer or cascade the 2 triple timers instead?

**Comment by ValiValpas** [comment]
Well, after a good night's sleep I noticed that I was totally wrong about my previous post. In other words, there was a PEBKAC issue with my prescaling implementation. Fixed it and `run/signal` is working properly now.

**Comment by m-stein** [comment]
Cool that you've found the problem with the timer. The fix-up looks good. Anyhow, if I didn't miss a thing, the maximum timeout is now ~31 ms which is still pretty low. We should keep this in mind if there are future performance/timing issues on Zynq.

**Comment by nfeske** [comment]
@m-stein I think that 31 milliseconds are just fine. Please keep in mind that the timer driver is shared my many components. In most scenarios, there is at least one component (e.g., nitpicker) that triggers timeouts at a rate of 10 milliseconds. Only when the system is idle, the maximum timeout comes into effect. And even in this case, the costs for handling a timeout every 31 milliseconds is negligible, isn't it?

**Comment by m-stein** [comment]
Likely you're right... I'm a little bit overcautious :)

**Comment by m-stein** [comment]
@ValiValpas 
I fetched your current state, merged the fix-ups to make re-basing easier, re-based the commits then and added some minor style fixes. As we shouldn't wait until re-basing gets more difficult and there are still open issues with the NIC commit, I would strongly vote for merging only base- and timer-support (https://github.com/m-stein/genode/commit/58b7b11296e5b5fa94802d23b1631b644a129bb7, https://github.com/m-stein/genode/commit/7f56e545947a8810537837d79121c0347fb65afb, https://github.com/m-stein/genode/commit/a1cce903565b6e4346538687d51f5591ba578ee0) into mainline and creating a new issue for NIC support. Do you agree with this?

Please use my branch [1599_Add_Zynq_7000_support_for_QEMU](https://github.com/m-stein/genode/tree/1599_Add_Zynq_7000_support_for_QEMU) for amendments.

**Comment by ValiValpas** [comment]
@m-stein 
Agreed.

**Comment by m-stein** [comment]
@chelmuth Could you please merge https://github.com/m-stein/genode/commit/58b7b11296e5b5fa94802d23b1631b644a129bb7, https://github.com/m-stein/genode/commit/7f56e545947a8810537837d79121c0347fb65afb, https://github.com/m-stein/genode/commit/a1cce903565b6e4346538687d51f5591ba578ee0 ?

**Comment by chelmuth** [comment]
Merged three commits into staging. I'll also enable the platform in the buildbot.

**Comment by m-stein** [comment]
@chelmuth Thanks!

**Comment by m-stein** [comment]
@ValiValpas Sorry for messing up the author in the Zynq-related commits. In mainline, this will be corrected.

**Comment by m-stein** [comment]
@chelmuth Added two fix-ups https://github.com/m-stein/genode/commit/0f04e329d70a0f6b91dce1f5203d2e2d2989cb38 and https://github.com/m-stein/genode/commit/cf5fa5bf465636ac28cf9c5fbeb7eb7304328077.

**Comment by ValiValpas** [comment]
Great. Let me know if I can be of any help with the NIC support.

**Comment by m-stein** [comment]
@ValiValpas I moved the NIC discussion to the new issue #1667.

**Pull request closed without merging**
