### PR TITLE
A collection of fixes and cleanups for issue reported by clang 11

### PR DESCRIPTION
**Pull request by tworaz**
This patch series contains a small collection of fixes and cleanups for various problems reported by clang 11. All of the issues fixed here are pretty generic. At least some of the issues fixed here can also be reproduced when building Genode with GCC 10.

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks for the welcome cleanup. I merged all commits to staging while slightly shortening the first line of the commit messages to 50 characters. @tworaz do you approve?

**Comment by tworaz** [comment]
@nfeske Just did a quick check of the staging branch and everything looks fine to me. It'll be nice to reduce the number of patches I have on my clang experimentation branch :) Big thanks for merging this!

**Comment by nfeske** [comment]
I have to revert parts of the base-linux changes (the removal of member variables) because the members are actually used when building for BOARD=pc.

**Comment by nfeske** [comment]
Most of the commits have become part of Genode 20.11. Thanks @tworaz for contributing the fixes!

**Pull request closed without merging**
