### PR TITLE
Clang warnings

### PR DESCRIPTION
**Pull request by ehmry**
These are a few fixes for errors when compiling from Clang. All are optional and each can be cherry-pick independently.

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks @ehmry for the patches. I merged most of them to staging, in some cases with slightly tweaked commit messages (can you please check if you are ok with them?)

I haven't merged https://github.com/genodelabs/genode/pull/3564/commits/122b51f9f825c071544a40159f7f3ab09f6dc73d, and https://github.com/genodelabs/genode/pull/3564/commits/1119e98f01be8650bbc0e013b554cb20da63b888 yet.

For https://github.com/genodelabs/genode/pull/3564/commits/1119e98f01be8650bbc0e013b554cb20da63b888 I want to learn @cnuke's intention behind the use of macro. For https://github.com/genodelabs/genode/pull/3564/commits/122b51f9f825c071544a40159f7f3ab09f6dc73d, I'd like to review the patch together with @chelmuth.

@ehmry Do you know, what's the problem about the initialization of variable-sized arrays (https://github.com/genodelabs/genode/pull/3564/commits/6c47c9c37341a6a0bc53c7285cb9f24fa8cd3fe7)? Just curios. Is this just a limitation of clang or a legitimate risk?

**Comment by ehmry** [comment]
@nfeske I think the array initialization is just a limitation of Clang/LLVM, I wouldn't worry much about that one.

**Comment by chelmuth** [comment]
> For [1119e98](https://github.com/genodelabs/genode/commit/1119e98f01be8650bbc0e013b554cb20da63b888) I want to learn @cnuke's intention behind the use of macro.

According to
```
> echo "" | genode-x86-g++ -m32 -o - - -dD -E | grep __UINT64_C
#define __UINT64_C(c) c ## ULL
> echo "" | genode-x86-g++ -m64 -o - - -dD -E | grep __UINT64_C
#define __UINT64_C(c) c ## UL
```

GCC appends `UL` or `ULL` to the literal to ensure an appropriate 64-bit unsigned integer value. IMO we could just append `ULL` in all cases.

**Comment by cnuke** [comment]
@nfeske @chelmuth yes, replacing it with `ULL` should be fine.

**Comment by nfeske** [comment]
>  replacing it with ULL should be fine.

Alright. Merged as https://github.com/genodelabs/genode/commit/39e7907267e9b4b34e2d8007142a0ac950cd2ce7 to staging.

**Comment by nfeske** [comment]
I merged all commits except https://github.com/genodelabs/genode/pull/3564/commits/122b51f9f825c071544a40159f7f3ab09f6dc73d. I did not merge the latter because I don't understand how it is an improvement.

**Pull request closed without merging**
