### PR TITLE
Add support for keyboard and mouse input for virt_qemu boards

### PR DESCRIPTION
**Pull request by tworaz**
I've been using this driver for a while and decided it'd be good to finally upstream it. This should hopefully make virt_qemu boards much more usable when it comes to running interactive test scenarios like run/vim, or run/bash for example.

### CODE REVIEW

**Comment by tworaz** [comment]
@nfeske No problem. I'm fine with the changes you've made.

WRT demo.run strange input problems, I can't see anything unexpected on my end. I'm still on Qemu 6.0, however. I'll try update to a newer version and see if it changes the situation.

**Comment by nfeske** [comment]
> I'm fine with the changes you've made.

Thanks you for the feedback.

**Comment by tworaz** [comment]
@nfeske I did manage to update my setup to use Qemu 6.1.0 during the weekend. Unfortunately I don't see any strange input events. I did try run/demo. run/wm, run/vim, run/nano3d. All of them seem to work as expected WRT mouse and keyboard events. I used staging branch commit bea3e8b2c2bb77566ae37df69cfab7da55c6f850 when testing this.

**Comment by nfeske** [comment]
> Unfortunately I don't see any strange input events.

I suspect that the effect is similar to the one reported in https://github.com/genodelabs/genode/issues/2309#issuecomment-284860860. I'm running Qemu inside VirtualBox on top of Sculpt OS. So this may well be a problem of the stacking of two layers of virtualization. In my opinion, this is not a pressing problem since Qemu's SDL backend can easily be disabled in situations like mine. Then everything works.

**Comment by chelmuth** [comment]
Added ab476d96e47 virt_qemu: use "-device ramfb"

**Comment by nfeske** [comment]
This work is part of Genode 21.11. Thank you again @tworaz!

**Pull request closed without merging**
