### PR TITLE
Add VirtualBox support for hw_x86_64_muen

### PR DESCRIPTION
**Pull request by reet-**
This patch sets enables hardware accelerated execution of guest VMs using VirtualBox on hw_x86_64_muen.

The Muen port is updated to the latest revision in order to have all necessary kernel features available for the hw_x86_64_muen/vbox scenario. Note that this version of Muen requires the GNAT/SPARK GPL 2016 toolchain.

Aside from the limitations listed below, the implementation is on par with VirtualBox on NOVA. The code is tested on our autopilot instance daily and the vbox_auto_win7* and vbox_auto_win8 scenarios pass.

Current limitations:
- No guest SMP support
- No support for 64-bit Windows
- Guest additions required for usable graphics output

### CODE REVIEW

**Comment by chelmuth** [comment]
@skalk please review 9635844d19edfe7e38c6411a0a930068c20ed816 189f6ec53fc4c342feb46d59d81ee9dcc4eb2703 467326e8bed1803e7824c86e92445176f34c5b55 fe2db21415a362de1848e36db8faa9d248f07776 0fc61799a982f58e9c9f684f970b25a1e1d8e3e2

@alex-ab any remarks to 12e473b370410e327adb8c5bf021a64767f7e682 0c0ffa1ed60eeddc992e1b44d8b255c9c90ec6dc b84fda1238e350ac3e032a467cdc164407d246c9 7b13172b544e0b590dc860953a90530b11573821 cfc0d3881bace07141f7d8d3a0b5fc0c98f3169c cb04b5b39d174e9ac3cfe15f5f3444647e6ef4c5 9e4a942234c837ddf64d527c2bbb7ec7cb7b6f0b ?

**Comment by alex-ab** [comment]
@chelmuth: I'm fine with the vbox changes - :_( but not with the vbox 5 re-do pain ;-)

**Comment by chelmuth** [comment]
@alex-ab that's unfortunate for sure and the sooner we update to VirtualBox 5 the better.

**Comment by skalk** [comment]
@chelmuth I'm fine with it

**Comment by chelmuth** [comment]
I merged the series and added a small fixup in c1d05a3.

**Comment by alex-ab** [comment]
Merged to master.

**Pull request closed without merging**
