### PR TITLE
hw_x86_64_muen: Add support for Message Signaled Interrupts

### PR DESCRIPTION
**Pull request by reet-**
This patch set adds support for MSIs to the `hw_x86_64_muen` platform.

The  first patch enables the ACPI functionality in the platform_drv on `hw_x86_64_muen` and
provides a simple generated XML report as ROM session in order to make the PCI configuration space available.

The base-hw `Irq_session_component` class is  extended with member variables to support MSI mode of operation. Values for MSI are only returned if the private `_is_msi` member is set to true.

The platform-specific MSI code is factored out to the `get_msi_params` function which returns false if either the platform or the device does not support MSI mode of operation.

The Muen Sinfo API is extended to retrieve PCI device information via the  `get_dev_info` function. The provided information is required to calculate MSI address/data register values in remappable format (see Intel VT-d specification, section 5.1.2.2).

The `get_msi_params` function on `hw_x86_64_muen` implements support for MSIs by using information provided via the `Sinfo::get_dev_info` function.

The changes are tested with the autopilot tool  for both `hw_x86_64` and `hw_x86_64_muen`.

### CODE REVIEW

**Comment by m-stein** [comment]
@reet- 
Thank you for these clean commits! I have only some minor suggestions on this. First, are the three fixups that I uploaded OK for you? Additionally, I would suggest to avoid bit logic like it is used by `to_sid` and `to_msi_addr` in `x86_64/muen/platform_support.cc` via the means of the Genode Register/MMIO framework (`util/register.h`, `util/mmio.h`). What do you think?

**Comment by reet-** [comment]
@m-stein
The fixups are certainly fine, thanks for that! I will squash them into my branch and then rewrite the `to_sid` and `to_msi_addr` functions to use the Register/MMIO framework if this is ok for you.

**Comment by reet-** [comment]
@m-stein 
As no registers or MMIO regions are involved, I fail to see how the current `to_sid`/`to_msi_addr` code can be simplified by using the Register/MMIO framework. Could you please provide some hints or even better, a concrete code example?

**Comment by chelmuth** [comment]
@m-stein may we merge this line of work into staging before the release?

**Comment by m-stein** [comment]
@reet- I've added a fixup that illustrates the use of the Register framework. What do you think about it? Could you please test it? It's a little bit more bureaucracy to do it this way but at the other hand it would be more descriptive and type safe I think.

I have not found any names for the bitfields in the VT specs, thus `Bits_0`/`Bits_1`. But I found that handle[15] shall be mapped to MSI-address[2] whereas the previous implementation `... | (handle & 0x8000) << 2;` looked to me as if it is mapped to MSI-address[17]. The Register implementation fixes that. Did I miss a thing here?

**Comment by reet-** [comment]
@m-stein Thanks for the fixup illustrating the use of the Register framework as a replacement for bit logic operations. I think it is not actually easier to read, but the fact that you found a bit logic error in the previous implementation shows that the solution is cleaner.

The relevant autopilot tests pass.

**Comment by m-stein** [comment]
@reet- Thank you for giving it a try :)

**Comment by chelmuth** [comment]
Merged the commits to staging just now.

**Comment by m-stein** [comment]
@chelmuth Added a fixup for RISCV.

**Pull request closed without merging**
