### PR TITLE
Add filenames to code snippets in hello_tutorial. Fixes #1369

### LINKED ISSUE #1369: hello_tutorial: Some of the filenames are not given
I just went through the hello tutorial, which was very helpful in understanding how the code is organized and how the Genode architecture works. However, not all of the code snippets have filenames specified, which means that I needed to grep the hello_tutorial included in the source tree to figure out where some of the code was supposed to go.

### PR DESCRIPTION
**Pull request by wolfgang42**
This fixes the missing filenames for the code snippets in hello_tutorial, as explained in #1369.

### CODE REVIEW

**Comment by nfeske** [comment]
@wolfgang42 Thank you very much for reporting the missing pieces and fixing it right away. This is greatly appreciated and I'd like  to merge your commit. However, we cannot incorporate anonymous patches into the mainline repository. Would you consider to use a valid email address in your patch? Right now, you configured git to use "wolfgang42@git" as email address.

**Comment by nfeske** [comment]
In case you prefer to remain anonymous, would you be fine with me committing the patch in my name?

**Comment by wolfgang42** [comment]
Sorry about that, I missed your first comment. I've pushed a new commit with the correct email address.

**Comment by nfeske** [comment]
Thanks! I merged the commit into the staging branch and will close the issue once it reaches the master branch.

**Comment by wolfgang42** [comment]
It looks like this reached master.

**Comment by nfeske** [comment]
Hehe... thanks for closing the issue ;-)

**Pull request closed without merging**
