### PR TITLE
Ali make dependencies

### PR DESCRIPTION
**Pull request by senier**
This is a major overhaul of the way Ada components are built. Most notable changes:

1. The Ada runtime ('ada') was renamed to 'spark'. While not formally correct (the SPARK subset is unrelated and bigger than the functionality supported by the runtime), this emphasizes the main purpose of that runtime: trusted components that get formally verified. Soon, I'll add another "fat" runtime under the name 'ada' in world to facilitate complex Ada programs.

2. The use of the `gnatmake` tool was dropped in favor of regular compiler calls as for the other languages. The tool is deprecated and it lead to corruption of `.ali` files in parallel builds resulting in sporadic broken builds.

3. Ada/SPARK programs are now bound using `gnatbind`. This leads to proper elaboration code being generated. It also has the benefit of providing proper error messages if sources are missing our outdated.

4. To facilitate consistent rebuilds on source code changes, we created the [ali2dep](https://github.com/Componolit/ali2dep) tool. From an `.ali` file, it creates `.d` files suitable for inclusion into make files. As `.ali` files do *not* contain absolute paths, search paths for all source files need to be provided on the command line.

   At the moment, `ali2dep` needs to be provided through the `CUSTOM_ALI2DEP` variable (absolute path or command name if the command is in `PATH`). By default a warning about the absence of the tool is emitted and dependencies are not generated. Eventually, `ali2dep` should become a part of Genode's toolchain and be called unconditionally.

I'll need help on one issue that remains unsolved in the current state. The above description only applies to "regular" builds, i.e. non-depot builds. The issue here is that `gnatbind` and `ali2dep` need to find all sources and `.ali` files mentioned in the currently processed `.ali` file. While the `api` package contains all the required sources, `.ali` files are merely build artifacts like `.o` files at the moment. We need to put the `.ali` files created during compilation into the API of the package (is that the right place?). Honestly, I have no idea how to do that, as those are created during compilation of the `src` package.

### CODE REVIEW

**Comment by nfeske** [comment]
That's super cool!

**Comment by nfeske** [comment]
I merged your excellent commit series to staging and just gave it a spin. Works splendidly! This makes the use of SPARK within Genode much more natural and comfortable. Thank you.

**Comment by chelmuth** [comment]
Without ali2dep, the changes work for `make -C build/x86_64 test/spark_exception test/spark test/spark_secondary_stack test/gnatio` but unfortunately fail when building depot archives.

```
> ./tool/depot/create CROSS_DEV_PREFIX=genode-x86- UPDATE_VERSIONS=1 FORCE=1 REBUILD= -j8 genodelabs/bin/x86_64/test-spark_exception genodelabs/bin/x86_64/test-spark_secondary_stack genodelabs/bin/x86_64/test-spark genodelabs/bin/x86_64/test-gnatio
created genodelabs/api/terminal_session/2018-02-12
created genodelabs/api/base/2019-02-13
created genodelabs/api/spark/2019-02-13
created genodelabs/src/test-spark_exception/2019-02-13-a
created genodelabs/src/test-gnatio/2019-02-13-a
created genodelabs/src/test-spark_secondary_stack/2019-02-13-a
created genodelabs/src/test-spark/2019-02-13-a
checking library dependencies...
checking library dependencies...
checking library dependencies...
checking library dependencies...
  Library ldso-startup
    COMPILE  startup.o
    COMPILE  startup.o
  Library ldso-startup
    MERGE    ldso-startup.lib.a
    MERGE    ldso-startup.lib.a
    COMPILE  startup.o
  Library ldso-startup
    MERGE    ldso-startup.lib.a
  Library ldso-startup
    COMPILE  startup.o
  Library spark
  Library ld
    CONVERT  ld.symbols.s
    MERGE    ldso-startup.lib.a
    CONVERT  spark.symbols.s
  Library spark
    CONVERT  ld.symbols.s
  Library ld
    ASSEMBLE spark.symbols.o
  Library spark
    CONVERT  spark.symbols.s
    CONVERT  spark.symbols.s
    ASSEMBLE ld.symbols.o
    ASSEMBLE spark.symbols.o
  Library ld
  Library ld
    ASSEMBLE ld.symbols.o
    ASSEMBLE spark.symbols.o
  Library spark
    CONVERT  ld.symbols.s
    CONVERT  ld.symbols.s
    MERGE    ld.abi.so
    MERGE    spark.abi.so
    CONVERT  spark.symbols.s
    MERGE    spark.abi.so
    ASSEMBLE ld.symbols.o
    MERGE    spark.abi.so
    ASSEMBLE ld.symbols.o
    ASSEMBLE spark.symbols.o
    MERGE    ld.abi.so
  Library base
    MERGE    base.lib.a
    MERGE    spark.abi.so
    MERGE    ld.abi.so
  Library base
    MERGE    base.lib.a
    MERGE    ld.abi.so
  Program test/gnatio/test-gnatio
    COMPILE  main.o
  Program test/spark_exception/test-spark_exception
    COMPILE  startup.o
    COMPILE  except.o
  Library base
    COMPILE  main.o
    MERGE    base.lib.a
  Library base
    MERGE    base.lib.a
  Program test/spark_secondary_stack/test-spark_secondary_stack
    COMPILE  stack.o
    COMPILE  main.o
        WARNING: ali2dep not used, get it from https://github.com/Componolit/ali2dep and make CUSTOM_ALI2DEP point to the binary.
genode-x86-gnatbind: Cannot find: s-stalib.ali
.../repos/base/mk/prg.mk:118: recipe for target 'b~test-gnatio.adb' failed
make[6]: *** [b~test-gnatio.adb] Error 4
var/libdeps:99: recipe for target 'test-gnatio.prg' failed
make[5]: *** [test-gnatio.prg] Error 2
Makefile:282: recipe for target 'gen_deps_and_build_targets' failed
make[4]: *** [gen_deps_and_build_targets] Error 2
    COMPILE  add_package.o
        WARNING: ali2dep not used, get it from https://github.com/Componolit/ali2dep and make CUSTOM_ALI2DEP point to the binary.
  Library test-spark
.../depot/genodelabs/src/test-spark_secondary_stack/2019-02-13-a/src/test/spark_secondary_stack/stack.adb:1:06: file "ss_utils.ads" not found
.../tool/depot/mk/build_bin_archive:187: recipe for target '.../depot/genodelabs/bin/x86_64/test-gnatio/2019-02-13-a.build/bin' failed
.../depot/genodelabs/src/test-spark_secondary_stack/2019-02-13-a/src/test/spark_secondary_stack/stack.adb:1:06: "Stack (body)" depends on "System.Secondary_Stack (spec)"
make[3]: *** [.../depot/genodelabs/bin/x86_64/test-gnatio/2019-02-13-a.build/bin] Error 1
.../depot/genodelabs/src/test-spark_secondary_stack/2019-02-13-a/src/test/spark_secondary_stack/stack.adb:1:06: "System.Secondary_Stack (spec)" depends on "Ss_Utils (spec)"
.../depot/genodelabs/src/test-spark_secondary_stack/2019-02-13-a/src/test/spark_secondary_stack/stack.adb:25:09: run-time library configuration error
.../depot/genodelabs/src/test-spark_secondary_stack/2019-02-13-a/src/test/spark_secondary_stack/stack.adb:25:09: file s-secsta.ads had semantic errors
.../depot/genodelabs/src/test-spark_secondary_stack/2019-02-13-a/src/test/spark_secondary_stack/stack.adb:25:09: entity "System.Secondary_Stack.Ss_Mark" not available
.../depot/genodelabs/api/spark/2019-02-13/ada-runtime/src/s-secsta.ads:13:14: "Ss_Utils" is undefined (more references follow)
.../depot/var/build.mk:24: recipe for target 'genodelabs/bin/x86_64/test-gnatio/2019-02-13-a' failed
compilation abandoned
make[2]: *** [genodelabs/bin/x86_64/test-gnatio/2019-02-13-a] Error 2
make[2]: *** Waiting for unfinished jobs....
genode-x86-gnatbind: Cannot find: s-stalib.ali
.../repos/base/mk/generic.mk:86: recipe for target 'stack.o' failed
make[6]: *** [stack.o] Error 1
.../repos/base/mk/prg.mk:118: recipe for target 'b~test-spark_exception.adb' failed
make[6]: *** [b~test-spark_exception.adb] Error 4
var/libdeps:99: recipe for target 'test-spark_secondary_stack.prg' failed
make[5]: *** [test-spark_secondary_stack.prg] Error 2
var/libdeps:99: recipe for target 'test-spark_exception.prg' failed
make[5]: *** [test-spark_exception.prg] Error 2
Makefile:282: recipe for target 'gen_deps_and_build_targets' failed
make[4]: *** [gen_deps_and_build_targets] Error 2
Makefile:282: recipe for target 'gen_deps_and_build_targets' failed
make[4]: *** [gen_deps_and_build_targets] Error 2
.../tool/depot/mk/build_bin_archive:187: recipe for target '.../depot/genodelabs/bin/x86_64/test-spark_secondary_stack/2019-02-13-a.build/bin' failed
make[3]: *** [.../depot/genodelabs/bin/x86_64/test-spark_secondary_stack/2019-02-13-a.build/bin] Error 1
.../depot/var/build.mk:24: recipe for target 'genodelabs/bin/x86_64/test-spark_secondary_stack/2019-02-13-a' failed
make[2]: *** [genodelabs/bin/x86_64/test-spark_secondary_stack/2019-02-13-a] Error 2
.../tool/depot/mk/build_bin_archive:187: recipe for target '.../depot/genodelabs/bin/x86_64/test-spark_exception/2019-02-13-a.build/bin' failed
make[3]: *** [.../depot/genodelabs/bin/x86_64/test-spark_exception/2019-02-13-a.build/bin] Error 1
.../depot/var/build.mk:24: recipe for target 'genodelabs/bin/x86_64/test-spark_exception/2019-02-13-a' failed
make[2]: *** [genodelabs/bin/x86_64/test-spark_exception/2019-02-13-a] Error 2
        WARNING: ali2dep not used, get it from https://github.com/Componolit/ali2dep and make CUSTOM_ALI2DEP point to the binary.
    MERGE    test-spark.lib.a
  Program test/spark/test-spark
    COMPILE  machinery.o
    COMPILE  main.o
    COMPILE  print.o
    COMPILE  startup.o
        WARNING: ali2dep not used, get it from https://github.com/Componolit/ali2dep and make CUSTOM_ALI2DEP point to the binary.
        WARNING: ali2dep not used, get it from https://github.com/Componolit/ali2dep and make CUSTOM_ALI2DEP point to the binary.
genode-x86-gnatbind: Cannot find: s-stalib.ali
.../repos/base/mk/prg.mk:118: recipe for target 'b~test-spark.adb' failed
make[6]: *** [b~test-spark.adb] Error 4
var/libdeps:118: recipe for target 'test-spark.prg' failed
make[5]: *** [test-spark.prg] Error 2
Makefile:282: recipe for target 'gen_deps_and_build_targets' failed
make[4]: *** [gen_deps_and_build_targets] Error 2
.../tool/depot/mk/build_bin_archive:187: recipe for target '.../depot/genodelabs/bin/x86_64/test-spark/2019-02-13-a.build/bin' failed
make[3]: *** [.../depot/genodelabs/bin/x86_64/test-spark/2019-02-13-a.build/bin] Error 1
.../depot/var/build.mk:24: recipe for target 'genodelabs/bin/x86_64/test-spark/2019-02-13-a' failed
make[2]: *** [genodelabs/bin/x86_64/test-spark/2019-02-13-a] Error 2
.../tool/depot/build:134: recipe for target 'execute_generated_build_mk_file' failed
make[1]: *** [execute_generated_build_mk_file] Error 2
tool/depot/create:59: recipe for target 'build' failed
make: *** [build] Error 2
``
```

@senier could you please look into this?

**Comment by senier** [comment]
This is expected and explained in the last paragraph of the PR. We first need a solution to make `.ali` files part of the API package. We should discuss that, as I don't have a good idea on how to implement that properly...

**Comment by nfeske** [comment]
> We need to put the .ali files created during compilation into the API of the package (is that the right place?). Honestly, I have no idea how to do that, as those are created during compilation of the src package.

The situation seems to be very similar to the ABI symbols. Those files are typically created with an successfully built shared object as input. (using `nm` or the `abi_symbols` tool) This is a manual step. I guess that the creation of the ali files for a given Ada library would also become such a manual step. To reduce the hassle to a manageable level, such ali files should be CPU-architecture agnostic if possible. So we should investigate whether this is feasible or not. Or maybe it suffices to have same kind of minimized ali files that contain only the information that are strictly needed? Also, I'm wondering what would be an appropriate location for those files? Somewhere at `include/<libname>/`?

Another question: When building depot archives, the ali2dep tool can be left out, right? My rationale is that the dependency tracking is not important in this situation because a given src archive does never change. So a partial build (where the .d files would come into play) cannot not happen. In this case, it would nevertheless be nice to somehow dim the noise of the ali2dep warnings. But that is just a cosmetic issue.

**Comment by nfeske** [comment]
Thanks @senier for the handling of the ali files. The binary archives for test-spark and test-spark_exceptions are now built w/o problem.

Unfortunately, there is still a build issue for test-spark_secondary_stack though:

```
$ ./tool/depot/create x/bin/x86_64/test-spark_secondary_stack UPDATE_VERSIONS=1 FORCE=1

...

/.../depot/x/src/test-spark_secondary_stack/2019-02-15/src/test/spark_secondary_stack/stack.adb:1:06: file "ss_utils.ads" not found
/.../depot/x/src/test-spark_secondary_stack/2019-02-15/src/test/spark_secondary_stack/stack.adb:1:06: "Stack (body)" depends on "System.Secondary_Stack (spec)"
/.../depot/x/src/test-spark_secondary_stack/2019-02-15/src/test/spark_secondary_stack/stack.adb:1:06: "System.Secondary_Stack (spec)" depends on "Ss_Utils (spec)"
/.../depot/x/src/test-spark_secondary_stack/2019-02-15/src/test/spark_secondary_stack/stack.adb:25:09: run-time library configuration error
/.../depot/x/src/test-spark_secondary_stack/2019-02-15/src/test/spark_secondary_stack/stack.adb:25:09: file s-secsta.ads had semantic errors
/.../depot/x/src/test-spark_secondary_stack/2019-02-15/src/test/spark_secondary_stack/stack.adb:25:09: entity "System.Secondary_Stack.Ss_Mark" not available
/.../depot/x/api/spark/2019-02-14/ada-runtime/src/minimal/s-secsta.ads:13:14: "Ss_Utils" is undefined (more references follow)
compilation abandoned
/plain/no/genode.git/repos/base/mk/generic.mk:86: recipe for target 'stack.o' failed
make[6]: *** [stack.o] Error 1
```

**Comment by nfeske** [comment]
Btw, the spark and spark_exception test did not only build successfully, they also ran successfully last night. ;-)

**Comment by senier** [comment]
Running in addition to building is always nice to have ;-) The issue with the third test should be fixed now.

**Comment by nfeske** [comment]
Thanks, merged to staging.

**Comment by m-stein** [comment]
:+1:

**Comment by nfeske** [comment]
The nightly builder has trouble with building test/spark_secondary_stack:

```
error: "s-conca2.ali" not found, "s-conca2.adb" must be compiled
error: "s-conca3.ali" not found, "s-conca3.adb" must be compiled
```

This problem is reported for various platforms/architectures (e.g., x86_64, x86_32, rpi).
The adb files come from the ada-runtime. There are no corresponding ali files in lib/ali.

Unfortunately, I'm not able to reproduce the build problem locally. When building locally, no traces of those files show up in the log.

**Comment by senier** [comment]
That is strange. The `s-concat*` package seem to contain optimization for string concatenation the compiler may choose to use. I never needed them so far. Is there anything special in the nightly builds (e.g. compiler flags that optimize for space)?

**Comment by nfeske** [comment]
@alex-ab Indeed. As part of the nightly builder, the whole tree is built with -O0 in addition to using the default optimization level -O2. When adding the following line to etc/tools.conf, the issue can be reproduced locally:

```
CC_OLEVEL := -O0
```

**Comment by senier** [comment]
Instead of adding more files to the runtime, I decided to disabled the optimization done when compiling with -O0. Consequently the SPARK code does not safe as much space as it could be, but we keep the runtime lean.

**Comment by nfeske** [comment]
@senier Thanks for the commit. I can confirm that it works. Merged to staging.

Now the only thing I'm missing in order to wrap up this pull request is the externalization of the ali files to somewhere outside the Genode repository.

**Comment by senier** [comment]
Done.

**Comment by nfeske** [comment]
Cool!

Would you mind me merging the content of ports/ada-runtime-alis.port into ports/ada-runtime.port? It is possible to let one port fetch content from multiple git repositories. This way, the distinction of the two repos would remain hidden from the user. The user would need to prepare only ada-runtime.

**Comment by senier** [comment]
Didn't know that's possible. Yes, that would definitely make things less verbose.

**Comment by nfeske** [comment]
While merging both port files, I just noticed that the ada-runtime.port still refers to AGPLv3. Should I update the LICENSE field to "AGPLv3  + GCC runtime library exception"?

**Comment by senier** [comment]
Yes, sure.

**Comment by nfeske** [comment]
Alright. Commit 2f9df922e2f0b5f9689bcc3c6e31be5b60e865c6 merges both port files.

**Comment by senier** [comment]
@nfeske I've got another fixup. It restores a feature to set a custom Ada compiler through a make variable. This is helpful when using a more modern GNAT, e.g. GNAT Community.

**Comment by nfeske** [comment]
Thanks, I merged your fixup to staging.

**Comment by nfeske** [comment]
Merged to master. I squashed the commit series (except for the first two ali2dep commits) into one commit 5ccae43552485e29dfc75f9557434955ba625867.

Thanks @senier for the excellent support while integrating the pull request!

**Pull request closed without merging**
