### PR TITLE
Upstream/clang fixes v2

### PR DESCRIPTION
**Pull request by tworaz**
This is another small collection of fixes for pretty generic and trivial issues raised by clang 11.

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks for the next batch of fixes.

To silence the warnings about unused arguments, removing the argument name instead of adding a new line like `(void)msg;` would avoid the addition of a new (and fairly uninteresting) line.

**Comment by tworaz** [comment]
@nfeske thanks for the suggestion. The problem should be fixed in the updated PR.

**Comment by ehmry** [comment]
FWIW Clang sometimes produces read-only ELF segments, which ld does not handle - 8c4bb7d84838e8c01673caa8ad45a4c042ccdd11.

**Comment by tworaz** [comment]
I think its not clang itself, but LLD.

**Comment by nfeske** [comment]
Thanks @tworaz. I merged your fixes with a few minor style tweaks.

**Comment by nfeske** [comment]
The fixes have become part of Genode 20.11.

**Pull request closed without merging**
