### PR TITLE
Add support for VirtIO drivers in Genode

### PR DESCRIPTION
**Pull request by tworaz**
This set of patches adds initial support for VirtIO device drivers in Genode. It first defines a new set of interfaces which VirtIO device drivers can use to locate, configure and manage VirtIO devices. The service side of these new interfaces is represented by a virtio_pci driver. The client side, aka device driver is represented by a nic driver. This driver should be fully capable of running all existing Genode networking scenarios.

In order to actually make it possible to use the newly introduced nic driver in existing qemu based networking scenarios I've did a bit of code consolidation around qemu nic setup code.

Since PCI support in Genode is right now limited to x86_64, which already has tested and working nic drivers, I've decided not to make this new nic driver a default one for x86_64 qemu machines. To use this new driver one has to manually add "virtio" to etc/specs.conf. After than scenarios like ping, fetchurl, nic_router_flood should automatically use the new driver.

In order to keep this patch set as simple as possible I've decided to not include virtio MMIO bus implementation initially. It would allow the nic driver to also work on recently added qemu virt machines. The MMIO based bus driver I've implemented does require Flatten Device Tree parser which according to @nfeske might need some consideration. I'll submit a separate PR for FDT and VirtIO MMIO support once this patch set lands on staging.

I wasn't sure how to best submit this since the patches depend on each other. If required I can submit them individually.

### CODE REVIEW

**Comment by skalk** [comment]
Thank you @tworaz for sharing your thoughts and VirtIO work with us. I will review your pull request carefully within the next days.

**Comment by skalk** [comment]
@tworaz Thanks again for your contribution! I really like to read your carefully drafted and sane code. Especially that you first cleanup the usage of NIC in Qemu scenarios within the run-scripts.

Nevertheless, I'm hesitating to take your pull request one-by-one, because of the introduction of the Virtio session interface. When reading through your commits, I've seen that you spend a lot of effort into this, which cuts me to the quick. But we try to limit the uncontrolled growth of session interfaces within Genode. In fact, one of the strengths of the framework is to have only few interfaces re-used at different places. That is why, we are very cautious nowadays to introduce new session interfaces, and better try to consolidate existing ones.

To me your Virtio session interface seems like a candidate for implementing the Platform_session/Platform_device interface. As you wrote in your commit messages, it is quite similar to the existent PCI interface, which is the Platform driver's interface currently used on x86. Please correct me if I'm wrong, or do not see specific things.

To me it seems like a good idea to consolidate the Virtio bus component together with the current consolidation work of the Platform driver (see issue #3299). Maybe we can also discuss the design in a separate issue. What do you think about this?

**Comment by tworaz** [comment]
@skalk I figured this might be the case given the discussions in #3299. I fully understand your reasoning and can't say I don't agree with it. Part of the reason virtio_session is a separate interface is I started working on it back in 2019 and at that time making Platform_session/Platform_device to also cover non-x86 platforms seemed like a too big task for me to handle. Certainly not something that I could attempt to do in my spare time.

Please feel free to take parts of this PR you think are useful and discard the rest for now. Once the  #3299 is done and the dust settles I'll try to re-write my code. Until that happens I'll keep using my virtio_session interface on my private work branch ;)

**Comment by skalk** [comment]
@tworaz I'm happy you take it like this. In case it gets urgent, I would cherry-pick parts from your topic branch. But I think forthe moment we can close the pull-request until the dust settled, as you phrased it ;-). Do you agree?
Apart from that, I still like to invite you to continuously share your view and needs regarding the platform driver API for a Virtio platform driver during this stage of design discussion in issue #3299.

**Comment by tworaz** [comment]
@skalk I'll close this PR then. Once again thanks for the time you took to look at this code.

**Pull request closed without merging**
