### PR TITLE
base-hw: add Zynq-7000 support

### PR DESCRIPTION
**Pull request by ValiValpas**
Supporting Qemu (hw_zynq), parallella board (hw_parallella) and zedboard
(hw_zedboard).

Device drivers: nic, gpio, vdma, i2c

Thanks to Timo Wischer and Mark Albers for their contributions.

### CODE REVIEW

**Comment by ValiValpas** [comment]
@skalk:

First of all, thanks for your appreciation.

Yes, I know about the GCA and Timo and Mark are happy to sign it.

We will certainly be working with the zedboard and the parallella for a while, thus we could play such a role for sure.

About splitting the commit: I don't have any objections. If I understand you correctly, you'll be taking care of this, or do you need me to take action here?

**Comment by skalk** [comment]
@ValiValpas: that is good news regarding the GCA, and especially your committment to maintain the board support for now.

Regarding the split of the commit: to be honest I would like you to do this, because otherwise it might take a while until I'm able to do so (time constraints), I can only test the QEMU variant, and lastly because, the majority of commits would loose their actual authorship. So if you do not mind I would be happy if you would continue to care for the commits primarily.

**Comment by ValiValpas** [comment]
@skalk: Alright then. It will probably take me a couple of days as well. Stay tuned!

**Comment by ValiValpas** [comment]
Closing this pull request because it is superseded by #1577

**Pull request closed without merging**
