### PR TITLE
base: added vsnprintf.

### PR DESCRIPTION
**Pull request by jklmnn**
Added vsnprintf to use va_lists directly with snprintf.

### CODE REVIEW

**Comment by nfeske** [comment]
One year ago, we decided to abolish format strings from Genode's base API. (see http://genode.org/documentation/release-notes/16.05#New_log-output_facilities) We still keep the functions around as some portions of the code still rely on them but they will ultimately be removed. For this reason, we are not going to extend them.

If you need `vsnprintf` in your application, please use the libc, which implements proper format string support (as opposed to the rather minimalistic subset provided by Genode's version). Should your component be a genuine Genode component, for which you'd like to avoid the dependency from the libc, please consider using the `Genode::String` constructor for assembling character strings.

**Comment by jklmnn** [comment]
As I'm creating a dde_linux driver, I think I'll go with the libc version, thanks.

**Comment by nfeske** [comment]
For a dde_linux driver, you may better use the printf implementation locally provided within the dde_linux repository. See `src/lx_kit/printf.cc` and `src/include/lx_emul/printf.h`. Pull requests for this version are welcome because it is meant to stay. ;-)

**Comment by ssumpf** [comment]
@jklmnn: For dde_linux it is recommended to implement the functions directly in dde_linux. `vsnprintf' is already implemented by the USB driver (src/lib/usb/lx_emul.cc) and the WIFI driver (src/lib/wifi/lxcc_emul.cc), you could simply copy a version into your driver, or since the function is used by more than one driver, we could also move into the lx_kit directory. Please don not link your driver against libc.

**Pull request closed without merging**
