### PR TITLE
Support GNAT.IO in Ada programs

### PR DESCRIPTION
**Pull request by senier**
This patch adds support for GNAT.IO in the Ada runtime. GNAT.IO is a stripped-down text I/O facility which we map to a terminal session on Genode (only output is supported at the moment). This is prepraratory work to port AUnit, a unit testing framework for Ada.

### CODE REVIEW

**Comment by nfeske** [comment]
Cool! I'm impressed that you went all the way of integrating your new test into the depot_autopilot.

The patch looks very good to me. I'd still like to wait with the merge until we have "mastered" the current staging branch.

**Comment by senier** [comment]
This looks like you're not using the latest Ada runtime. Can you please check whether the runtime is at Componolit/ada-runtime@6ebc27d7954eff4d027b3834f10a0934523c569b and `put_char` is present in `platform/genode.cc`?

**Comment by m-stein** [comment]
The previous version contained some GPS tmp files, sorry, fixed it:

9a13c5f fixup "Support GNAT.IO in Ada programs" (port hash)
efcd5a1 Support GNAT.IO in Ada programs

**Comment by senier** [comment]
> Cool! I'm impressed that you went all the way of integrating your new test into the depot_autopilot.
> 
> The patch looks very good to me. I'd still like to wait with the merge until we have "mastered" the current staging branch.

No problem, take your time.

**Comment by senier** [comment]
> The previous version contained some GPS tmp files, sorry, fixed it:
> 
> [9a13c5f](https://github.com/genodelabs/genode/commit/9a13c5f484ee7f575042381b2960e79225105cf8) fixup "Support GNAT.IO in Ada programs" (port hash)
> [efcd5a1](https://github.com/genodelabs/genode/commit/efcd5a1b5b374b8f861ce93932985320e5f4d9c1) Support GNAT.IO in Ada programs

Thanks! So, does the test succeed now on the targets you were mentioning?

**Comment by m-stein** [comment]
Yep. It does :)

**Comment by nfeske** [comment]
Too bad that the original commit has entered the master branch already. @m-stein Please create a new commit (not a fixup) with the follow-up patch.

**Comment by m-stein** [comment]
Done:
49dee1515a remove unused repos/app-file_cache* files

**Comment by nfeske** [comment]
Thanks. I pushed the new commit to staging.

**Comment by nfeske** [comment]
Merged in master.

**Pull request closed without merging**
