### PR TITLE
libc-vfs: support access

### PR DESCRIPTION
**Pull request by ehmry**

### CODE REVIEW

**Comment by ehmry** [comment]
Right now I'm pulling the access mode from the least signicant bits, ---|---|rwx, should I look at the 'user' bits or the 'other' bits? Or is this why access wasn't implemented?

**Comment by cnuke** [comment]
Actually, we do not care about the permission bits at that point because the permission to access the file system is enforced by the routing policy. Therefore, access merely should show if a path/file is accessible and should ignore any bits. It stands to reason if we really need to support UNIX permissions and up to now this question was answered with *no* since there is no notion of users on Genode.

**Comment by chelmuth** [comment]
Ah okay, so it boils down if any third-party application uses `access()` to implement program logic, right?

**Comment by cnuke** [comment]
Yes and if we want to support that we would probably have to do more than only checking the permissions in `access()`.

**Comment by ehmry** [comment]
Yea, I realize now that checking bits is pretty pointless.

**Pull request closed without merging**
