### PR TITLE
add blarson to depot

### PR DESCRIPTION
**Pull request by NobodyIII**
Here are the files for my depot repository. Could you please add these to the official Genode source tree?

### CODE REVIEW

**Comment by NobodyIII** [comment]
I tested this on my desktop computer, and it worked, but it doesn't work on my laptop. What could be going wrong?

**Comment by NobodyIII** [comment]
Okay, it looks like the issue is with git-lfs. I'll fix the repository today. Please go ahead and merge.

**Comment by nfeske** [comment]
Your commit has "Nobody III" as author. Would you consider changing your git settings such that your real name / email address appears as author?

**Comment by NobodyIII** [comment]
I changed it.

**Comment by nfeske** [comment]
Thanks. Merged to staging.

**Pull request closed without merging**
